server:
  port: 8081
spring:
  profiles:
    active: @env@
  redis:
    database: 1
    host: 123.56.23.97
    port: 6379
    password: redis123
    timeout: 5000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

  datasource:
    url: mysql.res.eqshow.cn:3306/eqs_enterprise_mgr_dev?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: YCs/VLcA7Pc7IcgjICuALT81P9rWfLSxAwvFLDrx9tNBRRNkleWdyVRYFH8AQcd76ZFVIprgopzHUIjNCy+E4A==
    driver-class-name: com.mysql.jdbc.Driver


#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  activemq:
#    broker-url: tcp://172.21.123.71:61616
#    in-memory: false
#    password: admin
#    user: admin
#    packages:
#      trust-all: false
#    pool:
#      enabled: false
#      expiry-timeout: 30000
#      max-connections: 1
